import { DynamicBreadcrumb } from "@/components/breadcrumb";
import { requireRoles } from "@/lib/auth-guard";
import OrganizationSidebar from "./OrganizationSidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perusahaan",
  description: "Generated by create next app",
};

const Organization = async () => {
  const session = await requireRoles(["USER"])
  return (
    <>
      <OrganizationSidebar user={session.user}>
        organization page
      </OrganizationSidebar>
    </>
  )
}

export default Organization