import { DynamicBreadcrumb } from "@/components/breadcrumb";
import { requireRoles } from "@/lib/auth-guard";
import OrganizationWrapper from "./OrganizationWrapper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perusahaan",
  description: "Generated by create next app",
};

const Organization = async () => {
  const session = await requireRoles(["USER"])
  return (
    <>
      <OrganizationWrapper user={session.user}>
        organization page
      </OrganizationWrapper>
    </>
  )
}

export default Organization