import { requireRoles } from "@/lib/auth-guard"
import AdminDashboard from "./(admin)/AdminDashboard"
import UserDashboard from "./(user)/UserDashboard"
import { Metadata } from "next";
import { getFullOrganization, getListOrganization } from "@/lib/organizations";

export async function generateMetadata(): Promise<Metadata> {
  const session = await requireRoles(['ADMIN', 'USER']);
  const userRole = session.user.role;

  const formattedRole = userRole.charAt(0).toUpperCase() + userRole.slice(1).toLowerCase();

  return {
    title: `Dashboard ${formattedRole}`,
    description: "Generated by create next app",
  };

}

const Dashboard = async () => {
  const session = await requireRoles(['ADMIN', 'USER'])
  const userRole = session.user.role
  const userId = session.user.id

  return (
    <>
      { userRole === 'ADMIN' && <AdminDashboard /> }
      { userRole === 'USER' && <UserDashboard /> }
    </>
  )
}

export default Dashboard