import { requireRoles } from "@/lib/auth-guard"
import AdminDashboard from "./(admin)/AdminDashboard"
import UserDashboard from "./(user)/UserDashboard"
import { Metadata } from "next";
import { getFullOrganization } from "@/lib/organizations";
import { redirect } from "next/navigation";
import prisma from "@/lib/prisma";

export async function generateMetadata(): Promise<Metadata> {
  const session = await requireRoles(['ADMIN', 'USER']);
  const userRole = session.user.role;

  const formattedRole = userRole.charAt(0).toUpperCase() + userRole.slice(1).toLowerCase();

  return {
    title: userRole === 'ADMIN' ? 'Trafina - Dashboard Admin' : 'Trafina - Dashboard',
    description: "Generated by create next app",
  };
}

const Dashboard = async () => {
  const session = await requireRoles(['ADMIN', 'USER'])
  const userRole = session.user.role

  if (userRole === 'USER') {
    const activeCompany = await getFullOrganization()
    if (!activeCompany) {
      redirect('/dashboard/com')
    }

    // Fetch transactions to calculate statistics
    const transactions = await prisma.transaction.findMany({
      where: { organizationId: activeCompany.id },
      orderBy: { createdAt: 'desc' }
    })

    // Fetch categories and payment methods for the add transaction modal
    const categories = await prisma.transactionCategory.findMany({
      where: { organizationId: activeCompany.id }
    })

    const paymentMethods = await prisma.paymentMethod.findMany({
      where: { organizationId: activeCompany.id }
    })

    const products = await prisma.product.findMany({
      where: { organizationId: activeCompany.id }
    })

    // Compute stats
    const totalIncome = transactions
      .filter(t => t.transactionType === 'INCOME')
      .reduce((sum, t) => sum + t.totalPrice, 0)

    const totalExpense = transactions
      .filter(t => t.transactionType === 'EXPENSE')
      .reduce((sum, t) => sum + t.totalPrice, 0)

    const balance = totalIncome - totalExpense

    // Calculate days since last transaction or company creation
    let belumMencatatHari = 0
    const lastTransaction = transactions[0]
    if (lastTransaction) {
      belumMencatatHari = Math.floor((Date.now() - new Date(lastTransaction.createdAt).getTime()) / (1000 * 60 * 60 * 24))
    } else {
      belumMencatatHari = Math.floor((Date.now() - new Date(activeCompany.createdAt).getTime()) / (1000 * 60 * 60 * 24))
    }

    // Deserialize or parse transactions dates for serializability across Server/Client boundary
    const serializedTransactions = transactions.map(t => ({
      ...t,
      createdAt: t.createdAt.toISOString(),
      updatedAt: t.updatedAt.toISOString(),
    }))

    const serializedCategories = categories.map(c => ({
      ...c,
      createdAt: c.createdAt.toISOString(),
      updatedAt: c.updatedAt.toISOString(),
    }))

    const serializedPaymentMethods = paymentMethods.map(p => ({
      ...p,
      createdAt: p.createdAt.toISOString(),
      updatedAt: p.updatedAt.toISOString(),
    }))

    const serializedProducts = products.map(p => ({
      ...p,
      createdAt: p.createdAt.toISOString(),
      updatedAt: p.updatedAt.toISOString(),
    }))

    return (
      <UserDashboard
        activeCompany={activeCompany}
        initialTransactions={serializedTransactions}
        categories={serializedCategories}
        paymentMethods={serializedPaymentMethods}
        products={serializedProducts}
        totalIncome={totalIncome}
        totalExpense={totalExpense}
        balance={balance}
        belumMencatatHari={belumMencatatHari}
      />
    )
  }

  return (
    <>
      { userRole === 'ADMIN' && <AdminDashboard /> }
    </>
  )
}

export default Dashboard
